version: "3.7"
services:
  frontend:
    image: ghcr.io/zisoo-choi/kdt1-study-3-team1-front:latest
    container_name: docker-frontend-deploy-server
    networks:
      - app
  
networks:
  app:
    driver: bridge